@server = https://crispy-couscous-w9g7wj45vfv6p9-8080.app.github.dev
@instrumentos = {{server}}/api/instrumentos
@musicos = {{server}}/api/musicos
###
GET {{instrumentos}}
###
POST {{instrumentos}}
Content-Type: application/json

{
  "nombre" : "Quena",
  "categoria" : "Instrumento de viento",
  "descripcion" : "tubo con orificios que al taparlos hacen sonar diferentes notas"
}
###
GET {{musicos}}
###
GET {{musicos}}/1
###
PATCH {{musicos}}/1
Content-Type: application/json

{
  "nombre" : "Jaime Hendrix"
}