@server = https://texai-musical-goldfish-q9pqwgxpjf4wvw-8080.preview.app.github.dev
@employees = {{server}}/api/employees
###
GET {{employees}}
###
POST {{employees}}
Content-Type: application/json

{
  "firstName" : "Bilbo",
  "lastName" : "Baggins",
  "description" : "burglar"
}